---
- name: check iptables version
  command: iptables --version
  register: iptables_version
  changed_when: false
  ignore_errors: true

- block:
    - name: Link iptables to /usr/sbin/iptables-legacy
      alternatives:
        name: iptables
        path: /usr/sbin/iptables-legacy

    - name: Link ip6tables to /usr/sbin/ip6tables-legacy
      alternatives:
        name: ip6tables
        path: /usr/sbin/ip6tables-legacy

    - name: Reboot initiated by Ansible for iptables-legacy
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible for iptables-legacy"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
  when: '"nf_tables" in iptables_version.stdout'
