---

- name: Enable firewall services
  service: 
    name: "{{ item }}" 
    state: started 
    enabled: yes
  with_items: "{{ firewall_services }}"
  ignore_errors: yes

- name: disable iptables-docker
  service:
    name: iptables-docker
    enabled: no
    state: stopped

- name: remove iptables-docker.sh
  file:
    path: /usr/local/sbin/iptables-docker.sh
    state: absent

- name: remove awk.firewall
  file:
    path: /usr/local/sbin/awk.firewall
    state: absent

- name: remove iptables-docker.service
  file:
    path: /etc/systemd/system/iptables-docker.service
    state: absent

- name: reload systemd
  systemd:
    daemon_reload: yes