---
name: Ansible Lint

permissions:
  contents: write

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Ansible Lint
        uses: ansible-community/ansible-lint-action@v6.0.1
      - name: Release
        if: github.ref == 'refs/heads/main' && startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1




