---
name: Lint and Release

permissions:
  contents: write

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Ansible Lint
        uses: ansible-community/ansible-lint-action@v6.0.1
      - name: Release
        if: startsWith(github.ref, 'refs/tags/0.')
        uses: softprops/action-gh-release@v1
      - name: Upload to Galaxy
        if: startsWith(github.ref, 'refs/tags/0.')
        uses: robertdebock/galaxy-action@1.1.0
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}




